2021-12-02 23:05:53,464 INFO    MainThread:41973 [wandb_setup.py:_flush():71] setting env: {}
2021-12-02 23:05:53,464 INFO    MainThread:41973 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-02 23:05:53,464 INFO    MainThread:41973 [wandb_init.py:_log_setup():371] Logging user logs to /Users/shy/Library/Mobile Documents/com~apple~CloudDocs/my python programming projects/DTI_pro/wandb/run-20211202_230553-1664xnmv/logs/debug.log
2021-12-02 23:05:53,465 INFO    MainThread:41973 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/shy/Library/Mobile Documents/com~apple~CloudDocs/my python programming projects/DTI_pro/wandb/run-20211202_230553-1664xnmv/logs/debug-internal.log
2021-12-02 23:05:53,465 INFO    MainThread:41973 [wandb_init.py:init():404] calling init triggers
2021-12-02 23:05:53,465 INFO    MainThread:41973 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'max_epochs': 150, 'batch_size': 100}
2021-12-02 23:05:53,465 INFO    MainThread:41973 [wandb_init.py:init():449] starting backend
2021-12-02 23:05:53,465 INFO    MainThread:41973 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-02 23:05:53,478 INFO    MainThread:41973 [backend.py:ensure_launched():199] starting backend process...
2021-12-02 23:05:53,486 INFO    MainThread:41973 [backend.py:ensure_launched():205] started backend process with pid: 41991
2021-12-02 23:05:53,495 INFO    MainThread:41973 [wandb_init.py:init():458] backend started and connected
2021-12-02 23:05:53,497 INFO    MainThread:41973 [wandb_init.py:init():519] updated telemetry
2021-12-02 23:05:53,510 INFO    MainThread:41973 [wandb_init.py:init():549] communicating current version
2021-12-02 23:05:54,650 INFO    MainThread:41973 [wandb_init.py:init():554] got version response 
2021-12-02 23:05:54,651 INFO    MainThread:41973 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-02 23:05:54,895 INFO    MainThread:41973 [wandb_init.py:init():592] starting run threads in backend
2021-12-02 23:05:57,467 INFO    MainThread:41973 [wandb_run.py:_console_start():1816] atexit reg
2021-12-02 23:05:57,468 INFO    MainThread:41973 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2021-12-02 23:05:57,468 INFO    MainThread:41973 [wandb_run.py:_redirect():1695] Redirecting console.
2021-12-02 23:05:57,469 INFO    MainThread:41973 [wandb_run.py:_redirect():1751] Redirects installed.
2021-12-02 23:05:57,470 INFO    MainThread:41973 [wandb_init.py:init():619] run started, returning control to user process
2021-12-02 23:05:57,470 INFO    MainThread:41973 [wandb_watch.py:watch():43] Watching
2021-12-02 23:05:57,476 INFO    MainThread:41973 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2021-12-02 23:05:57,477 INFO    MainThread:41973 [wandb_run.py:_restore():1758] restore
2021-12-02 23:06:00,001 INFO    MainThread:41973 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 804
  total_bytes: 804
}

2021-12-02 23:06:00,242 INFO    MainThread:41973 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 804
  total_bytes: 804
}

2021-12-02 23:06:00,931 INFO    MainThread:41973 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 804
  total_bytes: 6814
}

2021-12-02 23:06:01,038 INFO    MainThread:41973 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 804
  total_bytes: 7346
}

2021-12-02 23:06:01,145 INFO    MainThread:41973 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 804
  total_bytes: 7346
}

2021-12-02 23:06:01,246 INFO    MainThread:41973 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7346
  total_bytes: 7346
}

2021-12-02 23:06:01,347 INFO    MainThread:41973 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7346
  total_bytes: 7346
}

2021-12-02 23:06:01,454 INFO    MainThread:41973 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7346
  total_bytes: 7346
}

2021-12-02 23:06:01,559 INFO    MainThread:41973 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7346
  total_bytes: 7346
}

2021-12-02 23:06:01,664 INFO    MainThread:41973 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7346
  total_bytes: 7346
}

2021-12-02 23:06:01,919 INFO    MainThread:41973 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7346
  total_bytes: 7346
}

2021-12-02 23:06:02,418 INFO    MainThread:41973 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7346
  total_bytes: 7346
}
local_info {
}

2021-12-02 23:06:03,716 INFO    MainThread:41973 [wandb_run.py:_append_files():2184] logging synced files
