2021-12-01 22:39:25,803 INFO    MainThread:21598 [wandb_setup.py:_flush():71] setting env: {}
2021-12-01 22:39:25,803 INFO    MainThread:21598 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-01 22:39:25,803 INFO    MainThread:21598 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2021-12-01 22:39:25,803 INFO    MainThread:21598 [wandb_init.py:_log_setup():371] Logging user logs to /Users/shy/Library/Mobile Documents/com~apple~CloudDocs/my python programming projects/DTI_pro/wandb/run-20211201_223925-3eatibks/logs/debug.log
2021-12-01 22:39:25,803 INFO    MainThread:21598 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/shy/Library/Mobile Documents/com~apple~CloudDocs/my python programming projects/DTI_pro/wandb/run-20211201_223925-3eatibks/logs/debug-internal.log
2021-12-01 22:39:25,803 INFO    MainThread:21598 [wandb_init.py:init():404] calling init triggers
2021-12-01 22:39:25,803 INFO    MainThread:21598 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'max_epochs': 150, 'batch_size': 100}
2021-12-01 22:39:25,803 INFO    MainThread:21598 [wandb_init.py:init():449] starting backend
2021-12-01 22:39:25,803 INFO    MainThread:21598 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-01 22:39:25,819 INFO    MainThread:21598 [backend.py:ensure_launched():199] starting backend process...
2021-12-01 22:39:25,826 INFO    MainThread:21598 [backend.py:ensure_launched():205] started backend process with pid: 21663
2021-12-01 22:39:25,833 INFO    MainThread:21598 [wandb_init.py:init():458] backend started and connected
2021-12-01 22:39:25,835 INFO    MainThread:21598 [wandb_init.py:init():519] updated telemetry
2021-12-01 22:39:25,849 INFO    MainThread:21598 [wandb_init.py:init():549] communicating current version
2021-12-01 22:39:26,850 INFO    MainThread:21598 [wandb_init.py:init():554] got version response 
2021-12-01 22:39:26,850 INFO    MainThread:21598 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-01 22:39:27,119 INFO    MainThread:21598 [wandb_init.py:init():592] starting run threads in backend
2021-12-01 22:39:29,661 INFO    MainThread:21598 [wandb_run.py:_console_start():1816] atexit reg
2021-12-01 22:39:29,662 INFO    MainThread:21598 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2021-12-01 22:39:29,662 INFO    MainThread:21598 [wandb_run.py:_redirect():1695] Redirecting console.
2021-12-01 22:39:29,663 INFO    MainThread:21598 [wandb_run.py:_redirect():1751] Redirects installed.
2021-12-01 22:39:29,664 INFO    MainThread:21598 [wandb_init.py:init():619] run started, returning control to user process
2021-12-01 22:39:29,664 INFO    MainThread:21598 [wandb_watch.py:watch():43] Watching
2021-12-01 22:39:29,667 INFO    MainThread:21598 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2021-12-01 22:39:29,667 INFO    MainThread:21598 [wandb_run.py:_restore():1758] restore
2021-12-01 22:39:32,185 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 802
  total_bytes: 802
}

2021-12-01 22:39:32,464 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 802
  total_bytes: 802
}

2021-12-01 22:39:33,151 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 802
  total_bytes: 5877
}

2021-12-01 22:39:33,256 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 802
  total_bytes: 5903
}

2021-12-01 22:39:33,364 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 802
  total_bytes: 5903
}

2021-12-01 22:39:33,469 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5903
  total_bytes: 5903
}

2021-12-01 22:39:33,574 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5903
  total_bytes: 5903
}

2021-12-01 22:39:33,681 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5903
  total_bytes: 5903
}

2021-12-01 22:39:33,785 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5903
  total_bytes: 5903
}

2021-12-01 22:39:33,889 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5903
  total_bytes: 5903
}

2021-12-01 22:39:33,995 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5903
  total_bytes: 5903
}

2021-12-01 22:39:34,221 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5903
  total_bytes: 5903
}

2021-12-01 22:39:34,729 INFO    MainThread:21598 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5903
  total_bytes: 5903
}
local_info {
}

2021-12-01 22:39:36,022 INFO    MainThread:21598 [wandb_run.py:_append_files():2184] logging synced files
